# Generated by Django 5.0.1 on 2024-01-30 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCulinaryLocation', '0005_account_address_bill_confirm_dish_food_menu_saletime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='tieu_de',
            new_name='title',
        ),
    ]
