# Generated by Django 4.2.9 on 2024-01-31 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCulinaryLocation', '0006_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
