# Generated by Django 4.2.9 on 2024-02-01 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCulinaryLocation', '0007_login_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
